version: '3'

services:
  mysqldb:
    platform: linux/amd64
    image: mysql:5.7
    container_name: AuthentificationDB
    environment:
      MYSQL_ROOT_PASSWORD: KMPCube
      MYSQL_DATABASE: Authentification
      MYSQL_USER: API
      MYSQL_PASSWORD: Kilabilon258!
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: AuthentificationPMA
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  cubeapi:
    platform: linux/amd64
    image: valden01/authentification
    ports:
      - 8080:8080
    environment:
      DB_SERVER: mysqldb
      DB_NAME: Authentification
      DB_USERNAME: API
      DB_PASSWORD: Kilabilon258!
    depends_on:
      - mysqldb
volumes:
  dbdata: